In [1]:
# 1 

import numpy as np
def backwdsub(A,b):
    n = len(b)
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(A[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [2]:
# 2

# 2-1
print("""
2-1)
x1 = 1
x2 = x1 + 0
x3 = x2 + x1
x4 = x3 + x2
x5 = x4 + x3
""")

# 2-2
n = 10
A = np.eye(n) + (-1)*np.eye(n, k=-1) + (-1)*np.eye(n, k=-2)
b = np.zeros(n)
b[0] =  1

print(f"""
2-2)
A:
{A}

b: {b}
""")

# 2-3
for k in range(0,n):    # Forward substitutution
    b[k] = (b[k] - np.dot(A[k,0:k],b[0:k]))/A[k,k]
    
print(f"""
2-3)
x: {b}
""")


2-1)
x1 = 1
x2 = x1 + 0
x3 = x2 + x1
x4 = x3 + x2
x5 = x4 + x3


2-2)
A:
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1. -1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1. -1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1. -1.  1.]]

b: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2-3)
x: [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.]



In [3]:
# 3

# 3-1
# A_N = (0.95)*A_(N-1) + (0.02)*B_(N-1)
# B_N = (0.05)*A_(N-1) + (0.98)*B_(N-1)

A = np.array([[0.95, 0.02],
              [0.05, 0.98]])

print(f"""
3-1)
A:
{A}
""")

# 3-2
from scipy.linalg import lu

p, l, u = lu(A)
print(f"""
3-2)
L:
{l}

U:
{u}
""")

# 3-3
b = np.array([300000., 240000.])
n = 2

for i in range(3):
    for k in range(0,n):    # Forward substitutution
        b[k] = (b[k] - np.dot(l[k,0:k],b[0:k]))

    for k in range(n-1,-1,-1):    # Backward substitution
        b[k] = (b[k] - np.dot(u[k,k+1:n],b[k+1:n]))/u[k,k]

print(f"""
3-3)
A: {round(b[0])}명
B: {round(b[1])}명
""")


3-1)
A:
[[0.95 0.02]
 [0.05 0.98]]


3-2)
L:
[[1.         0.        ]
 [0.05263158 1.        ]]

U:
[[0.95       0.02      ]
 [0.         0.97894737]]


3-3)
A: 335442명
B: 204558명

