In [1]:
# 1

from numpy import array, zeros, hstack, dot
from numpy.linalg import solve

amat = array([[ 1.0,  2.0,  4.0],
              [ 3.0,  8.0, 14.0],
              [ 2.0,  6.0, 13.0]])

bmat = array([[  3.0],
              [ 13.0],
              [  4.0]])

x = zeros(bmat.shape)

a = hstack((amat.copy(), bmat.copy()))

# 2nd row, 1st col
lam1 = a[1,0]/a[0,0]    # Define first lambda
a[1] = a[1] - lam1*a[0]    # Modify second row

# 3rd row, 1st col
lam2 = a[2,0]/a[0,0]
a[2] = a[2] - lam2*a[0]

# 3rd row, 2nd col
lam3 = a[2,1]/a[1,1]
a[2] = a[2] - lam3*a[1]

n = len(x)
b = a[:,n:]
a = a[:,:n]

for k in range(n-1,-1,-1):    # Backward substitutution
    x[k] = (b[k] - dot(a[k,k+1:n],x[k+1:n]))/a[k,k]

print(f'x\n{x}')
print(f"\nlinalg.solve(A,b):\n{solve(amat, bmat)}")

x
[[ 3.]
 [ 4.]
 [-2.]]

linalg.solve(A,b):
[[ 3.]
 [ 4.]
 [-2.]]


In [2]:
# 2 

from numpy import array, zeros, hstack, dot
from numpy.linalg import solve

amat = array([[ 0.0,  0.0,  2.0,  1.0,  2.0],
              [ 0.0,  1.0,  0.0,  2.0, -1.0],
              [ 1.0,  2.0,  0.0, -2.0,  0.0],
              [ 0.0,  0.0,  0.0, -1.0,  1.0],
              [ 0.0,  1.0, -1.0,  1.0, -1.0]])

bmat = array([[  1.0],[  1.0],[ -4.0],[ -2.0],[ -1.0]])

x = zeros(bmat.shape)

tmp = hstack((amat.copy(), bmat.copy()))

a = array([tmp[2],tmp[1],tmp[0],tmp[3],tmp[4]])

# 1st col
a[1] = a[1] - (a[1,0]/a[0,0])*a[0]
a[2] = a[2] - (a[2,0]/a[0,0])*a[0]
a[3] = a[3] - (a[3,0]/a[0,0])*a[0]
a[4] = a[4] - (a[4,0]/a[0,0])*a[0]

# 2nd col
a[2] = a[2] - (a[2,1]/a[1,1])*a[1]
a[3] = a[3] - (a[3,1]/a[1,1])*a[1]
a[4] = a[4] - (a[4,1]/a[1,1])*a[1]

# 3rd col
a[3] = a[3] - (a[3,2]/a[2,2])*a[2]
a[4] = a[4] - (a[4,2]/a[2,2])*a[2]

# 4th col
a[4] = a[4] - (a[4,3]/a[3,3])*a[3]

n = len(x)
b = a[:,n:]
a = a[:,:n]

for k in range(n-1,-1,-1):    # Backward substitutution
    x[k] = (b[k] - dot(a[k,k+1:n],x[k+1:n]))/a[k,k]

if(x == solve(amat,bmat)).all:
    print(f'A\n{amat}\n\nb\n{bmat}\n\nx\n{x}\n\nA@x:\n{(amat@x)}')

A
[[ 0.  0.  2.  1.  2.]
 [ 0.  1.  0.  2. -1.]
 [ 1.  2.  0. -2.  0.]
 [ 0.  0.  0. -1.  1.]
 [ 0.  1. -1.  1. -1.]]

b
[[ 1.]
 [ 1.]
 [-4.]
 [-2.]
 [-1.]]

x
[[ 2.]
 [-2.]
 [ 1.]
 [ 1.]
 [-1.]]

A@x:
[[ 1.]
 [ 1.]
 [-4.]
 [-2.]
 [-1.]]


In [3]:
# 3

from numpy import array, zeros, hstack, dot
from numpy.linalg import solve

amat = array([[ 1.0,  2.0,  4.0],
              [ 3.0,  8.0, 14.0],
              [ 2.0,  6.0, 13.0]])

bmat = array([[  3.0],
              [ 13.0],
              [  4.0]])

a = amat.copy()
b = bmat.copy()

def gauss_inv(a,b):
    x = zeros(b.shape)
    n = len(x)
    # Elimination phase
    for k in range(n-1,0,-1):
        for i in range(0,k):
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i] = a[i] - lam*a[k]
                b[i] = b[i] - lam*b[k]
    print(f"Lower triangular matrix:\n{a}") 
    # Back substitution
    for k in range(0,n):    # Forward substitutution
        x[k] = (b[k] - dot(a[k,0:k],x[0:k]))/a[k,k]

    return x

print(f"\ngauss_inv(A,b):\n{gauss_inv(a,b)}")
print(f"\nlinalg.solve(A,b):\n{solve(amat, bmat)}")

Lower triangular matrix:
[[ 0.3         0.          0.        ]
 [ 0.84615385  1.53846154  0.        ]
 [ 2.          6.         13.        ]]

gauss_inv(A,b):
[[ 3.]
 [ 4.]
 [-2.]]

linalg.solve(A,b):
[[ 3.]
 [ 4.]
 [-2.]]


In [4]:
# 4

from numpy import array, zeros, hstack, dot, eye
from numpy.linalg import solve

amat = array([[ 1.0,  2.0,  4.0],
              [ 3.0,  8.0, 14.0],
              [ 2.0,  6.0, 13.0]])

bmat = array([[  3.0],
              [ 13.0],
              [  4.0]])

a = amat.copy()
b = bmat.copy()

def LU(a,b):
    L = eye(len(b))
    x = zeros(b.shape)
    y = zeros(b.shape)
    n = len(x)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i] = a[i] - lam*a[k]
                L[i,k] = lam
    
    U = a.copy()
    for k in range(0,n):    # Forward substitutution
        y[k] = b[k] - dot(L[k,:k],y[:k])
    
    for k in range(n-1,-1,-1):    # Backward substitutution
        x[k] = (y[k] - dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    
    return x

print(f'A\n{amat}\n\nb\n{bmat}\n')
print(f"LU(A,b)\n{LU(a,b)}")
print(f"\nlinalg.solve(A,b):\n{solve(amat, bmat)}")

A
[[ 1.  2.  4.]
 [ 3.  8. 14.]
 [ 2.  6. 13.]]

b
[[ 3.]
 [13.]
 [ 4.]]

LU(A,b)
[[ 3.]
 [ 4.]
 [-2.]]

linalg.solve(A,b):
[[ 3.]
 [ 4.]
 [-2.]]


In [5]:
from numpy import array, sin, cos, deg2rad
from numpy.linalg import solve

g = 10.0; theta = deg2rad(40)
m1 = 10.0; m2 = 4.0; m3 = 5.0; m4 = 6.0
mu1 = 0.25; mu2 = 0.3; mu3 = 0.2;

a = array([[  1,  0,  0, m1],
           [ -1,  1,  0, m2],
           [  0, -1,  1, m3],
           [  0,  0, -1, m4]])

b = array([[  m1 * g * ( sin(theta) - mu1 * cos(theta) )],
           [  m2 * g * ( sin(theta) - mu2 * cos(theta) )],
           [  m3 * g * ( sin(theta) - mu3 * cos(theta) )],
           [ -m4 * g                                    ]])

ans = solve(a,b)

print(f'T1 = {round(ans[0][0],2)} N\nT2 = {round(ans[1][0],2)} N\nT3 = {round(ans[2][0],2)} N\n a =  {round(ans[3][0],2)} m/s^2\n')

T1 = 34.68 N
T2 = 47.02 N
T3 = 66.27 N
 a =  1.05 m/s^2

