In [1]:
# 1

import numpy as np
import math

def conjGrad(Av,b,tol=1.0e-9):
    n = len(b)
    x = np.zeros(n)
    r = b - Av@x
    s = r.copy()
    for i in range(n):
        u = Av@s
        alpha = np.dot(s,r)/np.dot(s,u)
        x = x + alpha*s
        r = b - Av@x
        if(math.sqrt(np.dot(r,r))) < tol:
            break 
        else:
            beta = -np.dot(r,u)/np.dot(s,u)
            s = r + beta*s
    
    return x,i

A = np.array([[ 2.,-1., 0., 0., 0.],
              [-1., 4.,-1., 0., 0.],
              [ 0.,-1., 4.,-1.,-2.],
              [ 0., 0.,-1., 2.,-1.],
              [ 0., 0.,-2.,-1., 3.]])
b = np.ones(5)/2.5

vsol, Int = conjGrad(A,b)

print(vsol)

[0.56 0.72 1.92 2.24 2.16]


In [2]:
# 2-1
import numpy as np
import math
from time import time

n = 10
A = - np.eye(n,k=-1) + 4*np.eye(n,k=0) - np.eye(n,k=1)
b = 5*np.ones(n); b[0] = 9

def conjGrad(Av,b,tol=1.0e-9):
    n = len(b)
    x = np.zeros(n)
    r = b - Av@x
    s = r.copy()
    for i in range(n):
        u = Av@s
        alpha = np.dot(s,r)/np.dot(s,u)
        x = x + alpha*s
        r = b - Av@x
        if(math.sqrt(np.dot(r,r))) < tol:
            break 
        else:
            beta = -np.dot(r,u)/np.dot(s,u)
            s = r + beta*s
    return x,i

start_time = time()
vsol, Int = conjGrad(A,b)
conj_time = time() - start_time

print(f"""
- Conjugate Gradiant method 
  time1: {conj_time}

{vsol}
""")
def gaussElimin(a, b):
    n = len(b)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - np.dot(a[k,k+1:n], b[k+1:n]))/a[k,k]
    return b

start_time = time()
vsol = gaussElimin(A,b)
gaus_time = time() - start_time

print(f"""
- Gauss Elimin method
  time2: {gaus_time}
  
{vsol}

time1/time2: {conj_time/gaus_time}""")


- Conjugate Gradiant method 
  time1: 0.0009932518005371094

[2.90191936 2.60767745 2.52879042 2.50748425 2.50114659 2.4971021
 2.48726181 2.45194513 2.3205187  1.83012968]


- Gauss Elimin method
  time2: 0.0004360675811767578
  
[2.90191936 2.60767745 2.52879042 2.50748425 2.50114659 2.4971021
 2.48726181 2.45194513 2.3205187  1.83012968]

time1/time2: 2.277747402952433


In [3]:
# 2-2

n = 10000
A = - np.eye(n,k=-1) + 4*np.eye(n,k=0) - np.eye(n,k=1)
b = 5*np.ones(n); b[0] = 9

start_time = time()
vsol, Int = conjGrad(A,b)
conj_time = time() - start_time

print(f"""
- Conjugate Gradiant method 
  time1: {conj_time}

{vsol}
""")

start_time = time()
vsol = gaussElimin(A,b)
gaus_time = time() - start_time

print(f"""
- Gauss Elimin method
  time2: {gaus_time}
  
{vsol}

time1/time2: {conj_time/gaus_time}""")


- Conjugate Gradiant method 
  time1: 0.5496501922607422

[2.90192379 2.60769515 2.52885683 ... 2.45190528 2.32050808 1.83012702]


- Gauss Elimin method
  time2: 15.566628456115723
  
[2.90192379 2.60769515 2.52885683 ... 2.45190528 2.32050808 1.83012702]

time1/time2: 0.0353095208644746


In [4]:
# 3
import numpy as np

A = np.array([[1.,0.,1.],
              [0.,1.,0.],
              [0.,0.,1.]])
b = np.array([0.,0.,1.])

x0 = np.array([-1.,0.,0.])
s0 = np.array([0.,0.,1.])  # 탐색 방향 벡터, search direction
r0 = b - A@x0    # Residual, 차이
a0 = s0@r0 / (s0@A@s0)    # Scaling factor
# Update x
x1 = x0 + a0*s0
print(x1)

print(f"\nlinalg.solve:{np.linalg.solve(A,b)}")

[-1.  0.  1.]

linalg.solve:[-1.  0.  1.]
