In [1]:
import numpy as np

# pointer

a1 = [1,2,3]
b1 = a1
b2 = a1.copy()
a1.append(2)

print(f'a1==b1: {a1==b1}')
print(f'a1==b2: {a1==b2}')

a1==b1: True
a1==b2: False


In [2]:
import time
time_start = time.time()

A = np.zeros((4000,4000))

for i in range(4000):
    for j in range(4000):
        A[i,j] += 1
        
time_finish = time.time()

print(f'Total elapsed time {time_finish-time_start}')

Total elapsed time 12.38908076286316


In [3]:
time_start = time.time()

A = np.zeros((4000,4000))
A += np.ones((4000,4000))

time_finish = time.time()

print(f'Total elapsed time {time_finish-time_start}')

Total elapsed time 0.287463903427124


In [4]:
# Algorithm for Gauss Elimination Method

A = np.random.rand(3,4)

a = A[0:3,0:3].copy()
b = A[:,3].copy()
ans = np.linalg.solve(a,b).copy()

n = len(a) # or a.shape[0]

print(f'Before a\n{a}\n')
print(f'Before b\n{b}\n')

# Elimination phase
for k in range(0,n-1):      # pivot rows  k = 0, 1, ... , n-2
    for i in range(k+1,n):  # i = k+1, k+2, ... , n-1
        if a[i,k] != 0.0:
            lam = a[i,k]/a[k,k]
            a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
            b[i] = b[i] - lam*b[k]
            
print(f'After a\n{a}\n')
print(f'After b\n{b}\n')

# Back substitution

x = np.zeros(n)

for k in range(n-1,-1,-1): # From end to beginning
    x[k] = (b[k] - np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    
print(f'x\n{x}')
print(f'solve\n{ans}')

Before a
[[0.56640583 0.42706713 0.08029074]
 [0.46555882 0.84953566 0.1148495 ]
 [0.3803615  0.36574816 0.84802447]]

Before b
[0.29975103 0.7461685  0.34505076]

After a
[[ 5.66405833e-01  4.27067133e-01  8.02907426e-02]
 [ 0.00000000e+00  4.98506667e-01  4.88543031e-02]
 [-5.55111512e-17  0.00000000e+00  7.86368465e-01]]

After b
[0.29975103 0.49978732 0.06459701]

x
[-0.23229055  0.99451857  0.08214598]
solve
[-0.23229055  0.99451857  0.08214598]


In [5]:
# make function
def gauss(a,b):
    n = len(b) # or a.shape[0]
    x = np.zeros(n)
    
    # Elimination phase
    for k in range(0,n-1):      # pivot rows  k = 0, 1, ... , n-2
        for i in range(k+1,n):  # i = k+1, k+2, ... , n-1
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
                b[i] = b[i] - lam*b[k]
                
    # Back substitution
    for k in range(n-1,-1,-1): # From end to beginning
        x[k] = (b[k] - np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    
    return x

In [12]:
# 실습문제: 가우스 소거법을 활용하여 하삼각 행렬을 만들어 봅시다.

def gauss_inv(a,b):
    n = len(b) # or a.shape[0]
    x = np.zeros(n)

    print(f'Before a\n{a}\n')
    print(f'Before b\n{b}\n')
    
    # Elimination phase
    for k in range(n-1,0,-1):       # pivot rows  k = 0, 1, ... , n-2
        for i in range(k-1,-1,-1):   # i = k+1, k+2, ... , n-1
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,:k+1] = a[i,:k+1] - lam*a[k,:k+1]
                b[i] = b[i] - lam*b[k]
                
    print(f'After a\n{a}\n')
    print(f'After b\n{b}\n')

    # Back substitution
    for k in range(0,n): # From beginning to end
        x[k] = (b[k] - np.dot(a[k,:k],x[:k]))/a[k,k]

    return x

A = np.random.rand(3,4)

a = A[0:3,0:3].copy()
b = A[:,3].copy()
ans = np.linalg.solve(a,b).copy()

print(f'x\n{gauss_inv(a,b)}')
print(f'solve\n{ans}')

Before a
[[0.67694567 0.2583753  0.64162011]
 [0.35075608 0.67254613 0.44704742]
 [0.78800058 0.60193781 0.99503756]]

Before b
[0.70989022 0.43033098 0.73626576]

After a
[[ 0.16777045  0.          0.        ]
 [-0.0032744   0.40210936  0.        ]
 [ 0.78800058  0.60193781  0.99503756]]

After b
[0.26725549 0.09954376 0.73626576]

x
[ 1.59298308  0.2605257  -0.67919657]
solve
[ 1.59298308  0.2605257  -0.67919657]


In [13]:
b1 = [1,2,3]
b2 = [2,3,4]

bmat1 = np.array([b1,b2])
bmat2 = np.vstack((b1,b2))

bt1 = bmat1.T
bt2 = bmat2.T

In [27]:
# gauss 루틴의 b를 행렬 형태로 받을 수 있게 코드를 바꾸시오

a = np.array([[1,2,3],
              [2,3,4],
              [3,4,5]])
b = np.array([[1,2],
              [2,3],
              [3,4]])


def gauss(a,b):
    n = len(b) # or a.shape[0]
    x = np.zeros([n,len(b[0])])
    print(f'Before a\n{a}\n')
    print(f'Before b\n{b}\n')
    # Elimination phase
    for k in range(0,n-1):      # pivot rows  k = 0, 1, ... , n-2
        for i in range(k+1,n):  # i = k+1, k+2, ... , n-1
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
                b[i,:] = b[i,:] - lam*b[k,:]
    print(f'After a\n{a}\n')
    print(f'After b\n{b}\n')
                
    # Back substitution
    for k in range(n-1,-1,-1): # From end to beginning
        x[k,0] = (b[k,0] - np.dot(a[k,k+1:n],x[k+1:n,0]))/a[k,k]
        x[k,1] = (b[k,1] - np.dot(a[k,k+1:n],x[k+1:n,1]))/a[k,k]
    
    return x

A = np.random.rand(3,5)

a = A[0:3,0:3].copy()
b = A[:,3:].copy()
ans = np.linalg.solve(A[0:3,0:3],A[:,3:]).copy()

print(f'x\n{gauss(a,b)}')
print(f'solve\n{ans}')

Before a
[[0.03590582 0.92842026 0.63496613]
 [0.50995124 0.7130299  0.47426485]
 [0.18792903 0.48512113 0.12932338]]

Before b
[[0.67217244 0.81609593]
 [0.70247507 0.38666818]
 [0.36252894 0.48447947]]

After a
[[  0.03590582   0.92842026   0.63496613]
 [  0.         -12.47282739  -8.54382001]
 [  0.           0.          -0.19776488]]

After b
[[  0.67217244   0.81609593]
 [ -8.84403125 -11.20390654]
 [ -0.05401202   0.14225134]]

x
[[ 0.39368025 -0.51770572]
 [ 0.52198343  1.39097855]
 [ 0.27311226 -0.71929522]]
solve
[[ 0.39368025 -0.51770572]
 [ 0.52198343  1.39097855]
 [ 0.27311226 -0.71929522]]


In [ ]:
# LU Decomposition Method