In [2]:
# example
'''
A = [4 3]
    [6 3]
    
L = [ 1  0]
    [L21 1]
    
U = [U11 U12]
    [ 0  U22]
    
A = [ U11        U12     ]
    [U11L21  L21U12 + U22]
    
U11 = 4
U12 = 3
4*L21 = 6
L21 = 6/4
6/4*3 + U22 = 3
U22 = -3/2
'''
import numpy as np

L = np.array([[1,0],[6/4,1]])
U = np.array([[4,3],[0,-3/2]])

L@U 

array([[4., 3.],
       [6., 3.]])

In [3]:
# 실습문제 1
# 다음 A를 LU분해 하고 L@U가 A가 되는지 확인하시오.

# scipy.linalg.lu()

"""
A = [1  4 1]
    [1  6 1]
    [2 -1 2]
"""

A = np.array([[1,4,1],[1,6,1],[2,-1,2]])

L = np.eye(3)
U = np.zeros((3,3))

U[0] = A[0].copy()
L[1:,0] = (A[1:,0]/U[0,0]).copy()
U[1,1:] = (A[1,1:]-U[0,1:]*L[1,0]).copy()
L[2,1] = ((A[2,1]-U[0,1]*L[2,0])/U[1,1]).copy()
U[2,2] = (A[2,2]-np.dot(U[:2,2],L[2,:2])).copy()

L@U

array([[ 1.,  4.,  1.],
       [ 1.,  6.,  1.],
       [ 2., -1.,  2.]])

In [45]:
from scipy.linalg import lu

In [46]:
lu(A)[0]
lu(A)[1]


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]), array([[1.        , 0.        , 0.        ],
        [0.5       , 1.        , 0.        ],
        [0.5       , 0.69230769, 1.        ]]), array([[ 2. , -1. ,  2. ],
        [ 0. ,  6.5,  0. ],
        [ 0. ,  0. ,  0. ]]))

In [35]:
L

array([[ 1. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ],
       [ 2. , -1.5,  1. ]])

In [36]:
U

array([[1. , 4. , 1. ],
       [0. , 6. , 1. ],
       [0. , 0. , 1.5]])

In [37]:
U[:2,2]

array([1., 1.])

array([ 2. , -1.5])