In [1]:
# 1. 복습
# 2. 가우스 소거법 ->  LU 분해법
# 3. 응용문제
# 4. (숄레스키)
#

In [2]:
from sympy import *
init_printing()

a11, a12, a13 = symbols('A_{11} A_{12} A_{13}')
a21, a22, a23 = symbols('A_{21} A_{22} A_{23}')
a31, a32, a33 = symbols('A_{31} A_{32} A_{33}')

A = Matrix([[a11, a12, a13],[a21, a22, a23],[a31, a32, a33]])

A

⎡A_{11}  A_{12}  A_{13}⎤
⎢                      ⎥
⎢A_{21}  A_{22}  A_{23}⎥
⎢                      ⎥
⎣A_{31}  A_{32}  A_{33}⎦

In [3]:
import numpy as np

A = np.array([[ 6, -4,  1],
              [-4,  6, -4],
              [ 1, -4,  6]])

B = A.copy()

B[[0,2]] = B[[2,0]]        # Row swap
B[:,[0,2]] = B[:,[2,0]]    # Column swap

In [6]:
def gauss(a,b):
    n = len(b) # or a.shape[0]
    x = np.zeros(b.shape)
    # Elimination phase
    for k in range(0,n-1):      # pivot rows  k = 0, 1, ... , n-2
        for i in range(k+1,n):  # i = k+1, k+2, ... , n-1
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
                b[i,:] = b[i,:] - lam*b[k,:]
    # Back substitution
    for k in range(n-1,-1,-1): # From end to beginning
        x[k,0] = (b[k,0] - np.dot(a[k,k+1:],x[k+1:,0]))/a[k,k]
        x[k,1] = (b[k,1] - np.dot(a[k,k+1:],x[k+1:,1]))/a[k,k]
    
    return x

In [9]:
A = np.array([[ 6, -4,  1],
              [-4,  6, -4],
              [ 1, -4,  6]])

B = np.array([[-14,  22],
              [ 36, -18],
              [  6,   7]])

ans = np.linalg.solve(A,B)

print(ans)
print(gauss(A,B))

# row2 -> row2 - lam1*row1
lam1 = A[1,0]/A[0,0]
A[1,:] = A[1,:] - lam1*A[0,:]
B[1,:] = B[1,:] - lam1*B[0,:]


# row3 -> row3 - lam2*row1
lam2 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam2*A[0,:]
B[2,:] = B[2,:] - lam2*B[0,:]


# row3 -> row3 - lam3*row2
lam3 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam3*A[1,:]
B[2,:] = B[2,:] - lam3*B[1,:]

x = np.zeros(B.shape)

x[2,0] = (B[2,0])/A[2,2]
x[1,0] = (B[1,0]-np.dot(A[1,2:],x[2:,0]))/A[1,1]
x[0,0] = (B[0,0]-np.dot(A[0,1:],x[1:,0]))/A[0,0]

x[2,1] = (B[2,1])/A[2,2]
x[1,1] = (B[1,1]-np.dot(A[1,2:],x[2:,1]))/A[1,1]
x[0,1] = (B[0,1]-np.dot(A[0,1:],x[1:,1]))/A[0,0]

print(A)
print(B)
print(x)

[[10.  3.]
 [22. -1.]
 [14.  0.]]
[[11.94444444  3.        ]
 [25.66666667 -1.        ]
 [17.          0.        ]]
[[ 6 -4  1]
 [ 0  3 -3]
 [ 0  0  2]]
[[-14  22]
 [ 26  -3]
 [ 34   0]]
[[11.94444444  3.        ]
 [25.66666667 -1.        ]
 [17.          0.        ]]


In [10]:
# A = L*U

A = np.array([[ 6, -4,  1],
              [-4,  6, -4],
              [ 1, -4,  6]])


A@A == np.dot(A,A)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A = L@U
A@x = b
L@U@x = b

y = U@x # 후진대입
L@y = b # 전진대입

