In [ ]:
# 대칭행렬

In [2]:
import numpy as np

c = np.array([-2.,-6,12.,-6.])
d = np.array([2.,5.,16.,-39.,14.])
e = c.copy()

b = np.array([1.,0.,0.,0.,0.])
# bv = np.zeros(5); bv[0] = 1

amat = np.diag(c,k=-1) + np.diag(d,k=0) + np.diag(e,k=1)

np.linalg.solve(amat,b)

array([1.36924494, 0.86924494, 0.2679558 , 0.07734807, 0.03314917])

In [3]:
from ch2 import *

In [4]:
gaussElimin(amat.copy(),b.copy())

array([1.36924494, 0.86924494, 0.2679558 , 0.07734807, 0.03314917])

In [5]:
LU = LUdecomp(amat.copy())
print('LU',LU)
LUsolve(LU,b.copy())

LU [[  2.    -2.     0.     0.     0.  ]
 [ -1.     3.    -6.     0.     0.  ]
 [  0.    -2.     4.    12.     0.  ]
 [  0.     0.     3.   -75.    -6.  ]
 [  0.     0.     0.     0.08  14.48]]


array([1.36924494, 0.86924494, 0.2679558 , 0.07734807, 0.03314917])

In [6]:
# 삼중대각

am = amat.copy()
bv = b.copy()
cv = c.copy()
dv = d.copy()
ev = e.copy()

LUdecomp3(cv,dv,ev)
LUsolve3(cv,dv,ev,bv)

array([1.36924494, 0.86924494, 0.2679558 , 0.07734807, 0.03314917])

In [ ]:
# 대칭행렬일때 (?)
# A, seq = LUdecompp(amat)

# L, D, U 를 찾으시오
# A = L @ U = L @ D @ LT 성질이 있다는 것을 기억하시오

A = np.array([[ 3, -3,  3],
              [-3,  5,  1],
              [ 3,  1, 10]])

