In [1]:
# LU 분해
# 응용문제
# 물리응용문제 몇가지
# 숄레스키 분해

In [2]:
from ch2 import *
from scipy.linalg import *
import numpy as np

# Example 2.7

amat = np.array([[ 3.0, -1.0,  4.0],
              [-2.0,  0.0,  5.0],
              [ 7.0,  2.0, -2.0]])

b = np.array([[ 6.0,  3.0,  7.0,],
              [-4.0,  2.0, -5.0]])

a = amat.copy()

lu, piv = lu_factor(a)

np.linalg.solve(a,b.T) == lu_solve((lu,piv),b.T)

# 2nd row, 1st col
lam1 = a[1,0]/a[0,0]    # Define first lambda
#a[1,:] = a[1,:] - lam1*a[0,:]    # Modify second row
a[1] = a[1] - lam1*a[0]    # Modify second row

# 3rd row, 1st col
lam2 = a[2,0]/a[0,0]    # Define second lambda
a[2] = a[2] - lam2*a[0]    # Modify third row

# 3rd row, 2nd col
lam3 = a[2,1]/a[1,1]    # Define second lambda
a[2] = a[2] - lam3*a[1]    # Modify third row

print('a \n', a)

U = a.copy()
L = np.zeros([3,3])

L = L + np.diag([1,1,1]) # L = np.eye(3)

L[1,0] = lam1
L[2,0] = lam2
L[2,1] = lam3

print('\nL\n', L)

print('L@U\n', L@U)

# 전진대입으로 y를 구함, L@y = b

b = np.array([ 6.0,  3.0,  7.0,])
n = len(b)
y = np.zeros(n)
x = np.zeros(n)

for k in range(0,n):    # Forward substitutution
    y[k] = b[k] - np.dot(L[k,0:k],y[0:k])
    
print('y\n',y)

# U@x = y

for k in range(n-1,-1,-1):
    x[k] = (y[k]-np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    
print('x\n',x)

print('ans\n',np.linalg.solve(amat,b))

a 
 [[ 3.         -1.          4.        ]
 [ 0.         -0.66666667  7.66666667]
 [ 0.          0.         38.5       ]]

L
 [[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 2.33333333 -6.5         1.        ]]
L@U
 [[ 3. -1.  4.]
 [-2.  0.  5.]
 [ 7.  2. -2.]]
y
 [ 6.   7.  38.5]
x
 [1. 1. 1.]
ans
 [1. 1. 1.]


In [6]:
# Example 2.5

import numpy as np

amat = np.array([[ 1.0,  4.0,  1.0],
                 [ 1.0,  6.0, -1.0],
                 [ 2.0, -1.0,  2.0]])

b = np.array([ 7.0, 13.0,  5.0,])

y = np.zeros(b.shape)
x = np.zeros(b.shape)

a = amat.copy()

# 2nd row, 1st col
lam1 = a[1,0]/a[0,0]    # Define first lambda
a[1] = a[1] - lam1*a[0]    # Modify second row

# 3rd row, 1st col
lam2 = a[2,0]/a[0,0]    # Define second lambda
a[2] = a[2] - lam2*a[0]    # Modify third row

# 3rd row, 2nd col
lam3 = a[2,1]/a[1,1]    # Define second lambda
a[2] = a[2] - lam3*a[1]    # Modify third row

U = a.copy()
L = np.eye(3)

L[1,0] = lam1
L[2,0] = lam2
L[2,1] = lam3

print('L@U == amat\n', L@U==amat)

for k in range(0,n):    # Forward substitutution
    y[k] = b[k] - np.dot(L[k,0:k],y[0:k])
    
for k in range(n-1,-1,-1):    # Backward substitutution
    x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    
ans = np.linalg.solve(amat,b)

print('\nx == ans\n',x==ans)
print('\nx\n',x)

L@U == amat
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

x == ans
 [ True  True  True]

x
 [ 5.  1. -2.]


In [ ]:
          T_{1} + m_{1}a = m_{1}g(sin(theta)- mu_{1} cos(theta))
- T_{1} + T_{2} + m_{2}a = m_{2}g(sin(theta)- mu_{2} cos(theta))
- T_{2} + T_{3} + m_{3}a = m_{3}g(sin(theta)- mu_{3} cos(theta))
        - T_{3} + m_{4}a = m_{4}g