In [1]:
# 응용문제
# 삼중대각 계수행렬
### 오중대각 대칭행렬, 피보팅.
# 응용문제


In [2]:
# 1

import numpy as np
A = np.array([[3.,-3.,3.],[-3.,5.,1.],[3.,1.,5.]])
B = np.array([[9.],[-7.],[12.]])
print("linalg.solve:\n",np.linalg.solve(A.copy(),B.copy()))

from ch2 import *
LU = LUdecomp(A.copy())
x = LUsolve(LU,B.copy())
print("\nLUsolve:\n",x)

from scipy.linalg import lu_factor, lu_solve
lu, piv = lu_factor(A.copy())
x = lu_solve((lu,piv),B.copy())
print("\nscipy.linalg.lu_solve:\n",x)

linalg.solve:
 [[3.5       ]
 [0.66666667]
 [0.16666667]]

LUsolve:
 [[3.5       ]
 [0.66666667]
 [0.16666667]]

scipy.linalg.lu_solve:
 [[3.5       ]
 [0.66666667]
 [0.16666667]]


In [3]:
# 2

A = np.array([[  4.,  8.,  20.],
              [  8., 13.,  16.],
              [ 20., 16., -91.]])
B = np.array([[   24.],
              [   18.],
              [ -119]])

LU = LUdecomp(A.copy())
x = LUsolve(LU,B.copy())
print(x)

[[-3.]
 [ 2.]
 [ 1.]]


In [4]:
# Sparse matrix

In [5]:
n = 3
c = np.ones(n-1)
e = 2*np.ones(n-1)
d = 4*np.ones(n)
b = np.ones(n)

D = np.diag(d)
E = np.diag(e,k=1)
C = np.diag(c,k=-1)

A = C + E + D

dp = np.zeros(n)
cp = np.zeros(n-1)
y = np.zeros(n)
x = np.zeros(n)

for k in range(1,n):
    lam = c[k-1]/d[k-1]
    dp[k] = d[k] - lam*e[k-1]
    cp[k-1] = lam
    
# 전진대입
y[0] = b[0]
for k in range(1,n):
    y[k] = b[k] - cp[k-1]*y[k-1]

# 후진대입
x[n-1] = y[n-1]/dp[n-1]
for k in range(n-2,-1,-1):
    x[k] = (y[k] - e[k]*x[k+1])/d[k]
    
A@x

array([1.        , 0.96428571, 1.        ])

In [6]:
# [2,1,0,0,0]
# [1,2,1,0,0]
# [0,1,2,1,0]
# [0,0,1,2,1]
# [0,0,0,1,2]

# b= [1,1,1,1,1]

# Solve using tridiagonal matrix solver:
# Find U, L, x
# In A*x = b

n = 5
A = 2*np.eye(n) + np.eye(n,k=-1) + np.eye(n,k=1)
b = np.ones(n)

def LU(a,b):
    L = np.eye(len(b))
    x = np.zeros(b.shape)
    y = np.zeros(b.shape)
    n = len(x)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i] = a[i] - lam*a[k]
                L[i,k] = lam
    
    U = a.copy()
    for k in range(0,n):    # Forward substitutution
        y[k] = b[k] - np.dot(L[k,:k],y[:k])
    
    for k in range(n-1,-1,-1):    # Backward substitutution
        x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    
    return x

A@LU(A.copy(),b)

array([1., 1., 1., 1., 1.])

In [7]:
n = 5
c = np.ones(n-1)
d = 2*np.ones(n)
e = np.ones(n-1)

b = np.ones(n)

cc,dd,ee = LUdecomp3(c,d,e)
LUsolve3(cc,dd,ee,b)

cmat = np.diag(cc,k=-1)
dmat = np.diag(dd)
emat = np.diag(ee,k=1)

L = cmat + np.eye(5)
U = dmat + emat

L@U

array([[2., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [0., 1., 2., 1., 0.],
       [0., 0., 1., 2., 1.],
       [0., 0., 0., 1., 2.]])

In [8]:
c = np.array([-2,-6,12,-6])
d = np.array([2,5,16,39,14])
e = np.array([-2,-6,12,-6])

D = np.diag(d)
E = np.diag(e,k=1)
C = np.diag(c,k=-1)

A = C + E + D

A

array([[ 2, -2,  0,  0,  0],
       [-2,  5, -6,  0,  0],
       [ 0, -6, 16, 12,  0],
       [ 0,  0, 12, 39, -6],
       [ 0,  0,  0, -6, 14]])