In [1]:
# 역행렬 복습.
# 반복 방법. Interative mathod
# 공액경사법. Conjugate gradient method

A@x = B

X becomes the inverse matrix when

A@X =B

In [2]:
import numpy as np

A = np.array([[  0.6, -0.4,  1.0],
              [ -0.3,  0.2,  0.5],
              [  0.6, -1.0,  0.5]])

B = np.eye(3)  # or np.identity(3)

In [3]:
from ch2 import *

LU, seq = LUdecompp(A.copy())
x0 = LUsolvee(LU,B.copy()[:,0],seq)
x1 = LUsolvee(LU,B.copy()[:,1],seq)
x2 = LUsolvee(LU,B.copy()[:,2],seq)

x = np.array([x0,x1,x2]).T

np.around(A@x,decimals=2)

array([[ 1., -0., -0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [4]:
n = len(A)
LU, seq = LUdecompp(A.copy())
x = np.zeros((n,n))

for i in range(n):
    x[:,i] = LUsolvee(LU,B.copy()[:,i],seq)
    
np.around(A@x,decimals=2)

array([[ 1., -0., -0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [5]:
def inverse(A):
    n = len(A)
    B = np.eye(n)
    LU, seq = LUdecompp(A.copy())
    X = np.zeros((n,n))

    for i in range(n):
        X[:,i] = LUsolvee(LU,B.copy()[:,i],seq)
        
    return X

np.around(A@inverse(A),decimals=2)

array([[ 1., -0., -0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [6]:
# LUdecomp3, LUsolve3

n = 6
c = -1*np.ones(n-1)
d = 2*np.ones(n); d[-1] = 5.
e = -1*np.ones(n-1)

A = np.diag(c,k=-1) + np.diag(d,k=0) + np.diag(e,k=1)

LUdecomp3(c,d,e)
ans = LUsolve3(c,d,e,np.eye(n))

print(f"""X
{ans}

A@X
{np.around(A@ans,decimals=2)}

""")

X
[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]

A@X
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1. -0.  0.  0.  0.]
 [-0. -0.  1.  0.  0. -0.]
 [ 0.  0. -0.  1.  0.  0.]
 [-0. -0.  0.  0.  1.  0.]
 [-0. -0.  0. -0. -0.  1.]]




In [7]:
# Interative mathod

In [8]:
x = np.zeros(3)

A = np.array([[4.,-1.,1.],[-1.,4.,-2.],[1.,-2.,4.]])
b = np.array([12.,-1.,5.])

np.linalg.solve(A,b)

array([3., 1., 1.])

In [9]:
x[0] = (1/A[0,0]) * (b[0] - (A[0,1] * x[1] + A[0,2] * x[2]))
x[1] = (1/A[1,1]) * (b[1] - (A[1,0] * x[0] + A[1,2] * x[2]))
x[2] = (1/A[2,2]) * (b[2] - (A[2,0] * x[0] + A[2,1] * x[1]))

x

array([3.  , 0.5 , 0.75])

In [10]:
x = np.array([5.5,2.,-0.5])

A = np.array([[ 3.,-3., 3],
              [-3., 5., 1.],
              [ 3.,-1., 5.]])

b = np.array([9.,-7.,12.])

np.linalg.solve(A,b)

array([ 5.5,  2. , -0.5])

In [11]:
x[0] = (  9. - ((-3.) * x[1] +   3. * x[2]))/3.
x[1] = (- 7. - ((-3.) * x[0] +   1. * x[2]))/5.
x[2] = ( 12. - (( 3.) * x[0] + (-1.) * x[1]))/5.

x

array([ 5.5,  2. , -0.5])

In [12]:
# Conjugate gradient method

In [13]:
x = np.zeros(3)

A = np.array([[4.,-1.,1.],[-1.,4.,-2.],[1.,-2.,4.]])
b = np.array([12.,-1.,5.])

In [14]:
x0 = x.copy()

# First iteration
r0 = b - A@x0    # Residual, 차이
s0 = r0.copy()    # 탐색 방향 벡터, search direction
a0 = s0@r0 / (s0@A@s0)    # Scaling factor
# Update x
x1 = x0 + a0*s0
print(x1)

# Second iteration
r1 = b - A@x1    # new residual
b0 = -r1@A@s0 / (s0@A@s0)    # search direction factor
s1 = r1 + b0*s0    # new search direction
a1 = s1@r1 / (s1@A@s1)    # scaling factor
# Update x
x2 = x1 + a1*s1
print(x2)

# Third iteration
r2 = b - A@x2    # new residual
b1 = -r2@A@s1 / (s1@A@s1)    # search direction factor
s2 = r2 + b1*s1    # new search direction
a2 = s2@r2 / (s2@A@s2)    # scaling factor
# Update x
x3 = x2 + a2*s2
print(x3)

[ 2.41706161 -0.2014218   1.007109  ]
[3.07752283 0.79483181 0.71998218]
[3. 1. 1.]


In [15]:
x = np.zeros(3)

A = np.array([[ 3.,-3., 3],
              [-3., 5., 1.],
              [ 3., 1., 5.]])

b = np.array([9.,-7.,12.])

print(np.linalg.solve(A,b))

[3.5        0.66666667 0.16666667]


In [16]:
x0 = x.copy()

# First iteration
r0 = b - A@x0    # Residual, 차이
s0 = r0.copy()    # 탐색 방향 벡터, search direction
a0 = s0@r0 / (s0@A@s0)    # Scaling factor
# Update x
x1 = x0 + a0*s0
print(x1)

# Second iteration
r1 = b - A@x1    # new residual
b0 = -r1@A@s0 / (s0@A@s0)    # search direction factor
s1 = r1 + b0*s0    # new search direction
a1 = s1@r1 / (s1@A@s1)    # scaling factor
# Update x
x2 = x1 + a1*s1
print(x2)

# Third iteration
r2 = b - A@x2    # new residual
b1 = -r2@A@s1 / (s1@A@s1)    # search direction factor
s2 = r2 + b1*s1    # new search direction
a2 = s2@r2 / (s2@A@s2)    # scaling factor
# Update x
x3 = x2 + a2*s2
print(x3)

[ 1.19361084 -0.92836399  1.59148112]
[ 18.34439265   3.8788959  -13.41230235]
[3.5        0.66666667 0.16666667]


In [17]:
def Av(v):
    return A@v

x0 = np.zeros(3)
conjGrad(Av,x0,b)

(array([3.5       , 0.66666667, 0.16666667]), 2)